In [1]:
# data pre-processing

In [103]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn import tree
import pickle

In [99]:
df = pd.read_csv("datafile.csv")
df.head(10)

,COMMODITIES,Weight,Apr-04,May-04,Jun-04,Jul-04,Aug-04,Sep-04,Oct-04,Nov-04,...,Mar-13,Apr-13,May-13,Jun-13,Jul-13,Aug-13,Sep-13,Oct-13,Nov-13,Dec-13
0,ALL COMMODITIES,100.00000,97.5,98.0,98.3,99.2,100.6,100.5,100.7,101.5,...,170.1,171.3,171.4,173.2,175.5,179.0,180.7,180.7,181.5,179.2
1,I PRIMARY ARTICLES,20.11815,97.0,98.5,99.0,101.0,103.5,102.2,102.9,103.7,...,223.1,226.5,227.3,233.9,240.3,251.9,252.7,251.4,256.3,243.6
2,(A) FOOD ARTICLES,14.33709,97.5,98.5,98.8,100.7,103.0,101.1,102.4,105.2,...,214.1,219.8,223.1,230.9,238.5,252.4,252.9,251.7,256.4,240.1
3,a. FOOD GRAINS(CEREALS+PULSES),4.08982,96.7,97.3,97.8,98.2,100.1,100.3,100.4,106.1,...,216.1,216.5,216.8,221.4,224.4,226.1,228.2,228.4,229.8,230.3
4,a1. CEREALS,3.37323,96.0,96.9,97.4,97.7,99.5,99.6,99.9,107.3,...,212.5,212.9,213.7,219.6,224.0,227.1,228.7,228.3,230.1,230.4
5,Rice,1.79348,96.9,97.8,98.7,98.9,99.7,100.3,101.1,100.7,...,206.2,207.6,210.9,218.7,226.3,231.5,231.4,232.0,232.5,230.3
6,Wheat,1.11595,94.8,95.0,95.6,95.4,98.4,98.8,99.0,121.7,...,205.4,203.6,200.8,205.2,206.6,208.7,212.9,213.6,217.1,220.5
7,Jowar,0.09572,93.4,99.1,98.6,99.9,104.6,98.6,99.0,100.4,...,250.7,253.2,251.6,246.9,245.7,241.2,241.6,241.5,247.1,252.7
8,Bajra,0.11522,96.2,96.5,94.5,98.5,99.5,98.1,98.9,99.9,...,257.7,263.7,267.0,265.4,261.9,252.2,252.4,251.7,251.0,252.5
9,Maize,0.21727,96.0,98.8,96.5,98.5,101.6,99.6,95.4,95.0,...,249.1,249.9,246.8,254.5,254.9,255.3,260.4,247.1,250.7,252.9

In [104]:
def getDataAccToCommodity(commodity):
    try:
        df1 = df[df['COMMODITIES'] == commodity]
        a = list(df1.iloc[0])
        prices = a[2:]
        commodity = a[0]
        weight = a[1]
        dates = list(df1.columns[2:])

        df2 = pd.DataFrame()
        df2['Date'] = dates
        df2['Prices'] = prices/weight
    except:
        df2 = pd.DataFrame()
    
    return df2

def getDateNum(date):
    a = date.split("-")
    month = a[0]
    year = int(a[1])
    num = year*12 + monthToNumber[month]
    return num

In [134]:
crops = ['Moong']
monthToNumber = {
    "Jan":1, "Feb":2, "Mar":3, "Apr":4, "May":5, "Jun":6, "Jul":7, "Aug":8, "Sep":9, "Oct":10, "Nov":11, "Dec":12
}

In [135]:
for crop in crops:
    data = getDataAccToCommodity(crop)
    data['DateModified'] = data["Date"].apply(lambda x: getDateNum(x))
    
    X = list(data["DateModified"])
    X = [[k] for k in X]
    y = data["Prices"]
    
    X = np.asarray(X)
    y = np.asarray(y)
    
    # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
    X_train, y_train = X, y
    
    clf = tree.DecisionTreeRegressor()
    clf = clf.fit(X_train, y_train)
    
    filename = crop+'.sav'
    pickle.dump(clf, open(filename, 'wb'))

In [136]:
import pickle
loaded_model = pickle.load(open('Moong.sav', 'rb'))

# inputs
year = 2021
month = 4
num = ((year-2000)*12)+month

price = loaded_model.predict([[num]])[0]
price

3773.87590461502